name: Terraform Apply & Destroy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy Application
        run: |
          # Your deployment scripts here
          # e.g., deploy to AWS, configure New Relic, etc.

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

